const { PGlite } = require(process.env.PGLITE_MODULE_PATH || '@electric-sql/pglite');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, 'supabase/migrations', name), 'utf8');
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
(async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      CREATE ROLE authenticated; CREATE ROLE anon; CREATE ROLE service_role;
      CREATE SCHEMA auth;
      CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      GRANT USAGE ON SCHEMA auth,public TO authenticated,anon;
      CREATE TABLE profiles(id uuid PRIMARY KEY,display_name text,avatar_url text);
      CREATE TABLE role_assignments(user_id uuid,role text,status text,end_date date,created_at timestamptz);
      CREATE FUNCTION is_instructor(uuid) RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM role_assignments WHERE user_id=$1 AND role='instructor' AND status='active' AND end_date IS NULL) $$;
      CREATE TABLE daily_records(user_id uuid,record_date date,attendance_status text,attendance_late boolean,meditation_submitted boolean,meditation_submitted_at timestamptz,meditation_public boolean);
      CREATE TABLE scripture_verse_insights(id uuid,user_id uuid,created_at timestamptz);
      CREATE TABLE daily_quote_comments(commenter_user_id uuid,created_at timestamptz);
      CREATE TABLE daily_verse_comments(commenter_user_id uuid,created_at timestamptz);
      CREATE TABLE scripture_insight_comments(user_id uuid,created_at timestamptz);
      CREATE TABLE daily_quote_reactions(reactor_user_id uuid,created_at timestamptz);
      CREATE TABLE daily_verse_reactions(reactor_user_id uuid,created_at timestamptz);
      CREATE TABLE scripture_insight_reactions(reactor_user_id uuid,created_at timestamptz,insight_id uuid,reaction_type text);
      CREATE TABLE public_scripture_insight_reactions(insight_id uuid,created_at timestamptz,reaction_type text);
      CREATE TABLE external_share_events(user_id uuid,created_at timestamptz);
      CREATE TABLE game_attempts(user_id uuid,score numeric,completed_at timestamptz,status text);
      CREATE TABLE arena_participants(user_id uuid,room_id uuid,score numeric,finished_at timestamptz);
      CREATE TABLE arena_rooms(id uuid,status text,winner_id uuid,completed_at timestamptz);
      CREATE TABLE quiz_attempts(user_id uuid,talents_scored numeric,submitted_at timestamptz,status text);
      CREATE TABLE story_mode_fig_entries(user_id uuid,figs numeric,earned_at timestamptz);
      CREATE TABLE tent_members(user_id uuid,tent_id uuid,role text,joined_at timestamptz);
      CREATE TABLE tents(id uuid,name text,profile_image_url text);
      CREATE TABLE fcx_events(id uuid,event_date date,event_month date,created_at timestamptz);
      CREATE TABLE fcx_registrations(event_id uuid,user_id uuid);
      CREATE TABLE awards(title text,user_id uuid,award_month text);
      CREATE FUNCTION get_lifetime_qualifying_streak_days(uuid,date) RETURNS bigint LANGUAGE sql STABLE AS $$ SELECT 10::bigint $$;
      CREATE FUNCTION get_qualifying_denarii_total(uuid,timestamptz) RETURNS numeric LANGUAGE sql STABLE AS $$ SELECT 20::numeric $$;
      CREATE FUNCTION get_user_lifetime_figs(uuid,timestamptz) RETURNS numeric LANGUAGE sql STABLE AS $$ SELECT 30::numeric $$;
      CREATE FUNCTION calculate_normalized_marks(numeric,numeric,numeric,numeric) RETURNS numeric LANGUAGE sql STABLE AS $$ SELECT 10::numeric $$;
      INSERT INTO profiles VALUES('${id(1)}','Instructor',NULL),('${id(2)}','Cadet One',NULL),('${id(3)}','Cadet Two',NULL),('${id(4)}','Sentry One',NULL),('${id(5)}','Former Cadet',NULL);
      INSERT INTO role_assignments VALUES('${id(1)}','instructor','active',NULL,now()),('${id(2)}','cadet','active',NULL,now()),('${id(3)}','cadet','approved',NULL,now()),('${id(4)}','cadet','active','2026-08-31',now()-interval '1 day'),('${id(4)}','sentry','active',NULL,now()),('${id(5)}','cadet','active','2026-08-31',now());
      INSERT INTO daily_records VALUES('${id(2)}','2026-09-01','present',false,true,'2026-09-01T19:00Z',true),('${id(3)}','2026-09-01','present',true,true,'2026-09-01T22:00Z',false),('${id(4)}','2026-09-01','present',false,true,'2026-09-01T19:00Z',true);
      INSERT INTO scripture_verse_insights VALUES('${id(10)}','${id(2)}','2026-08-31T23:00Z'),('${id(11)}','${id(2)}','2026-09-30T23:00Z');
      INSERT INTO daily_quote_comments VALUES('${id(2)}','2026-09-01T00:00Z');
      INSERT INTO daily_verse_reactions VALUES('${id(2)}','2026-09-01T00:00Z');
      INSERT INTO scripture_insight_reactions VALUES('${id(3)}','2026-09-01T00:00Z','${id(10)}','heart');
      INSERT INTO public_scripture_insight_reactions VALUES('${id(10)}','2026-09-02T00:00Z','heart');
      INSERT INTO external_share_events VALUES('${id(2)}','2026-09-02T00:00Z'),('${id(1)}','2026-09-02T00:00Z');
      INSERT INTO game_attempts VALUES('${id(2)}',5,'2026-09-02T00:00Z','passed'),('${id(2)}',99,NULL,'in_progress'),('${id(2)}',100,'2026-09-30T23:00Z','passed');
      INSERT INTO arena_rooms VALUES('${id(20)}','completed','${id(2)}','2026-09-02T00:00Z');
      INSERT INTO arena_participants VALUES('${id(2)}','${id(20)}',2,'2026-09-02T00:00Z');
      INSERT INTO quiz_attempts VALUES('${id(2)}',7,'2026-09-02T00:00Z','submitted'),('${id(3)}',17,'2026-09-02T00:00Z','submitted');
      INSERT INTO story_mode_fig_entries VALUES('${id(2)}',3,'2026-09-02T00:00Z');
      INSERT INTO tents VALUES('${id(30)}','Tent One',NULL),('${id(31)}','Tent Two',NULL);
      INSERT INTO tent_members VALUES('${id(2)}','${id(31)}','cadet','2026-08-01'),('${id(2)}','${id(30)}','cadet','2026-09-01'),('${id(3)}','${id(31)}','cadet','2026-09-01'),('${id(4)}','${id(30)}','sentry','2026-09-01');
      INSERT INTO fcx_events VALUES('${id(40)}','2026-08-30','2026-08-01','2026-08-01'),('${id(41)}','2099-09-30','2099-09-01','2026-09-01');
      INSERT INTO fcx_registrations VALUES('${id(40)}','${id(2)}'),('${id(40)}','${id(3)}'),('${id(40)}','${id(4)}'),('${id(41)}','${id(2)}');
    `);
    const messenger = read('20260920100000_award_cadence_visibility_and_rhetoric.sql');
    await db.exec(messenger.slice(messenger.indexOf('CREATE OR REPLACE FUNCTION public.get_monthly_messenger_award_metrics('), messenger.indexOf('CREATE OR REPLACE FUNCTION public.give_award(')));
    await db.exec(read('20260927072202_monthly_award_nominees.sql'));
    const as = async (n, role='authenticated') => {
      await db.exec('RESET ROLE');
      await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[n ? id(n) : '']);
      await db.exec(`SET ROLE ${role}`);
    };
    const nominees = () => db.query("SELECT * FROM get_monthly_award_nominees('2026-09-01')");
    await as(null,'anon'); await assert.rejects(nominees(),/permission denied/);
    await as(null); await assert.rejects(nominees(),/Instructor access required/);
    await as(2); await assert.rejects(nominees(),/Instructor access required/);
    await as(4); await assert.rejects(nominees(),/Instructor access required/);
    await as(1);
    const {rows} = await nominees();
    const category = title => rows.filter(r=>r.award_title===title);
    assert.equal(new Set(rows.map(r=>r.award_title)).size,7,'all monthly honors represented');
    assert.ok(rows.every(r=>![id(1),id(5)].includes(r.target_id)),'no instructor or ended-role nominees');
    assert.equal(category('Vallum')[0].target_id,id(2));
    assert.equal(Number(category('Vallum')[0].metric_value),14,'local month boundaries and punctuality');
    assert.equal(category('Monthly Scribe').length,2);
    assert.ok(category('Monthly Scribe').every(r=>Number(r.metric_value)===17 && r.is_leader),'all fig sources; equal totals are co-leaders');
    assert.equal(category('Monthly Valley Champion')[0].metric_value,'1');
    assert.equal(category('Centurion')[0].target_id,id(4),'separate sentry category');
    assert.equal(category('Messenger Award (Nuncio)')[0].metric_value,'4','member and guest reactions, meditation, share');
    assert.ok(category('Messenger Award (Nuncio)').every(r=>r.target_type==='cadet'));
    assert.equal(category('Bethel Stone')[0].target_id,id(30));
    assert.equal(category('Bethel Stone')[0].metric_value,'14','latest cadet membership only, no sentry duplication');
    assert.equal(category('Muralis').length,2);
    assert.ok(category('Muralis').every(r=>r.needs_selection && !r.is_leader),'no invented FCX winner');
    await db.exec('RESET ROLE');
    await db.exec(`INSERT INTO awards VALUES('Muralis','${id(3)}','2026-08')`);
    await as(1);
    const muralis=(await nominees()).rows.filter(r=>r.award_title==='Muralis');
    assert.equal(muralis[0].target_id,id(3)); assert.equal(muralis[0].is_leader,true);
    assert.equal((await db.query("SELECT count(*)::int n FROM get_monthly_award_nominees('2026-07-01') WHERE award_title NOT IN ('Vallum','Bethel Stone')")).rows[0].n,0,'no future activity in prior months');
    console.log('Monthly nominee DB tests passed: all seven categories, authorization, current roles, local month boundaries, ties, fig sources, FCX selection, and tent totals.');
  } finally { await db.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
